# Set temporary PATH locations
PATH="/usr/local/bin:/usr/bin:/bin"
[ -d ~/.config/zsh ] || mkdir -p ~/.config/zsh
export ZDOTDIR=~/.config/zsh
[ -d ~/.local/share/zsh ] || mkdir -p ~/.local/share/zsh
export HISTFILE=~/.local/share/zsh/history
export SAVEHIST=50
