#!/bin/sh -e
#
# Automatically create date-stamped btrfs snapshots of all btrfs filesystem in
# /etc/fstab
#

for uuid in $(findmnt -snrt btrfs -O subvol -o UUID | sort | uniq); do
    opts="$(findmnt -snrS UUID="$uuid" -O subvol -o OPTIONS | \
        sed -E 's/,*subvol=.*,*//' | sort | uniq)"
    mkdir -p /run/btrfs
    mount -t btrfs -o "$opts" "UUID=$uuid" /run/btrfs
    for subvol in $(findmnt -snrS "UUID=$uuid" -O subvol -o OPTIONS | \
        grep -Eo ',?subvol=.*,?' | tr -d , | cut -d= -f2); do
        if [ -d "/run/btrfs/${subvol}-$(date -I)" ]; then
	    echo "Skipping \"${subvol}\" subvolume: \"${subvol}-$(date -I)\" snapshot already exists!"
        else
	    (
	        cd /run/btrfs
                btrfs subvolume snapshot -r "$subvol" "${subvol}-$(date -I)"
	    )
        fi
    done
    umount /run/btrfs
    rmdir /run/btrfs
done
