#!/bin/sh
#
# Desktop-specific ssh-add invocations to be used in various desktop startup
# routines
#

case "$XDG_CURRENT_DESKTOP" in
    KDE)
        sleep 5 # Let KWallet finish initializing
        SSH_ASKPASS=/usr/bin/ksshaskpass exec ssh-add -q
        ;;
    *)
        echo "${0}: Unknown desktop: $XDG_SESSION_DESKTOP"
        ;;
esac
