#!/bin/sh
# dmenu prompt with some options to exit i3 then go to tty, poweroff, or reboot

# Saving the selection to a variable
EXIT="$(printf 'Yes\nPoweroff\nReboot' | dmenu -i -p 'Do you want to exit i3?' -nb '#323334' -sb '#285577')"

# Exiting i3 based on the selection above
case "$EXIT" in
    Yes) i3-msg exit ;;
    #Poweroff) i3-msg exit ; sudo shutdown -h -P now ;; # this is for slackware
    #Reboot) i3-msg exit ; sudo shutdown -r now ;; # this is for slackware
    Poweroff) i3-msg exit ; dbus-send --system --print-reply --dest="org.freedesktop.ConsoleKit" /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.Stop ;; # this is for Arch (systemd) / Obarun (s6)
    Reboot) i3-msg exit ; dbus-send --system --print-reply --dest="org.freedesktop.ConsoleKit" /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.Restart ;; # this is for Arch (systemd) / Obarun (s6)
esac
