#!/bin/sh -e
#
# Start s6-based user services upon first login
#

# Setting $PATH first since it's probably undefined
export PATH="/usr/bin:/bin:/usr/sbin:/sbin"

# Defining some important constants that will be used later
SYSTEM_SCANDIR="$(xargs -0a /proc/1/cmdline | grep -o ' /.*$' | cut -c 2-)"
USERTREE_SVNAME="usertree-$PAM_USER"
USERTREE_SVDIR="${SYSTEM_SCANDIR}/${USERTREE_SVNAME}-srv"
S6RC_TIMEOUT="5000"
USER_SCANDIR="${XDG_RUNTIME_DIR}/s6/service"
USER_S6RC_LIVE="${XDG_RUNTIME_DIR}/s6/rc"
USER_S6RC_BUNDLE="${XDG_SESSION_TYPE}-session" # unspecified/tty/x11/wayland/mir
USER_S6RC_COMPILED="/home/${PAM_USER}/.config/s6/rc/compiled"

# Aborting execution when not invoked by pam_exec
if [ -z "$PAM_SERVICE" ]; then
    echo "We are not invoked by pam_exec, aborting..."
    exit 1
fi

# Exiting immediately if PID 1 is not s6-svscan
grep -Fqwz s6-svscan /proc/1/cmdline || exit 0

# Exiting immediately if the user doesn't have a supervision tree configured
[ -d "$USERTREE_SVDIR" ] || exit 0

# Checking if this is not the user's first session
if [ $(loginctl -p Sessions --value show-user "$PAM_USER" | wc -w) -gt 1 ]; then
    # Exiting immediately if the user doesn't use s6-rc
    [ -d "$USER_S6RC_LIVE" ] || exit 0
    # Starting the appropriate user configured bundle (based on this session's
    # type) again in case the current and last sessions' type are different
    exec s6-setuidgid "$PAM_USER" \
        s6-rc -bl "$USER_S6RC_LIVE" -t "$S6RC_TIMEOUT" \
            change "$USER_S6RC_BUNDLE"
fi

# Starting the user's supervision tree
s6-rc -bt "$S6RC_TIMEOUT" change "$USERTREE_SVNAME"

# No need to continue further if the user doesn't use s6-rc
[ -d "$USER_S6RC_COMPILED" ] || exit 0

# Initializing s6-rc for the user's supervision tree
s6-setuidgid "$PAM_USER" \
    s6-rc-init -dc "$USER_S6RC_COMPILED" -l "$USER_S6RC_LIVE" \
        -t "$S6RC_TIMEOUT" "$USER_SCANDIR"

# Starting the appropriate user configured bundle (based on this session's type)
exec s6-setuidgid "$PAM_USER" \
    s6-rc -l "$USER_S6RC_LIVE" -t "$S6RC_TIMEOUT" change "$USER_S6RC_BUNDLE"
