#!/bin/sh -e

# Check for root permission
[ $(id -u) -ne 0 ] && echo "Run $0 as root!" && exit 1

# Check for arguments
[ $# -le 0 ] && echo "Pass directories as arguments!" && exit 1

# Export MAKEFLAGS
export MAKEFLAGS="${MAKEFLAGS:--j$(nproc)}"

# Give the user some time to cancel
echo Packages to build: "$(basename -a "$@" | tr '\n' ' ')"
echo MAKEFLAGS is set to: "$MAKEFLAGS"
printf "Continuing in: "
for i in $(seq -s " " 10 -1 1); do
    printf "%s " "$i"
    sleep 1
done
echo

# Start main loop
for dir in "$@"; do
    (
        cd "$dir"
        . ./*.info
        bash "${PRGNAM}.SlackBuild"
        upgradepkg --reinstall --install-new /tmp/"$PRGNAM"-"$VERSION"-*.t?z
    )
done
