#!/bin/sh

# Exit on error
set -e

# Check for arguments
[ $# -le 0 ] && echo Pass directories as arguments! && exit 1

# Start main loop
for dir in "$@"; do
    (
        cd "$dir"
        . ./*.info
        # Get source file extension
        EXT="$(echo ${DOWNLOAD##*/} | sed -E "s/${PRGNAM}.*${VERSION}\.//")"
        # Get the latest version
        LATEST="$(wget -qO- $(dirname $DOWNLOAD) | \
            grep -Eo "${PRGNAM}-.*\.${EXT}" | \
            sed "s/${PRGNAM}-//; s/\.${EXT}//")"
        if [ "$VERSION" = "$LATEST" ]; then
            echo "${PRGNAM}: Up to date (${LATEST})"
        else
            echo "${PRGNAM}: ${VERSION} -> ${LATEST}"
            sed -i "s/${VERSION}/${LATEST}/g" *.info *.SlackBuild
            . ./*.info
            wget -q --show-progress "$DOWNLOAD"
            NEWSUM="$(md5sum "$(basename "$DOWNLOAD")" | cut -d" " -f1)"
            sed -i "s/${MD5SUM}/${NEWSUM}/" *.info
        fi
    )
done
