#!/bin/sh -e

# Check for arguments
[ $# -le 0 ] && echo "Pass directories as arguments!" && exit 1

# Start main loop
for dir in "$@"; do
    [ -d "$dir" ] || continue
    (
        cd "$dir"
        . ./*.info
        # Get source file extension
        EXT="$(echo "${DOWNLOAD##*/}" | sed -E "s/${PRGNAM}.*${VERSION}\.//")"
        # Get the latest version
        LATEST="$(wget -qO- "$(dirname "$DOWNLOAD")" | \
            grep -Eo "${PRGNAM}-.*\.${EXT}" | \
            sed "s/${PRGNAM}-//; s/\.${EXT}//")"
        if [ "$VERSION" = "$LATEST" ]; then
            echo "${PRGNAM}: Up to date (${LATEST})"
        else
            echo "${PRGNAM}: ${VERSION} -> ${LATEST}"
            sed -i "s/${VERSION}/${LATEST}/g" "${PRGNAM}.info" \
                "${PRGNAM}.SlackBuild"
            . "./${PRGNAM}.info"
            if [ -f "$(basename "$DOWNLOAD")" ]; then
                echo "$(basename "$DOWNLOAD") already exists"
            else
                wget -q --show-progress "$DOWNLOAD"
            fi
            NEWSUM="$(md5sum "$(basename "$DOWNLOAD")" | cut -d" " -f1)"
            sed -i "s/${MD5SUM}/${NEWSUM}/" "${PRGNAM}.info"
        fi
    )
done
