#!/bin/sh

SINK=$(pactl list sinks | grep 'Sink #[^0]' | cut -d\# -f2)
if test -z $SINK; then
    SINK=$(pactl list sinks | grep 'Sink #0' | cut -d\# -f2)
fi

case "$1" in
    up) pactl set-sink-volume $SINK +1% ;;
    down) pactl set-sink-volume $SINK -1% ;;
    mute) pactl set-sink-mute $SINK toggle ;;
esac
