[ -d ~/.config/zsh ] || /bin/mkdir -p ~/.config/zsh
export ZDOTDIR=~/.config/zsh
[ -d ~/.local/share/zsh ] || /bin/mkdir -p ~/.local/share/zsh
export HISTFILE=~/.local/share/zsh/history
export SAVEHIST=100000
